"""API Data Transfer Models & Enums Package.

Contains Pydantic models for structured agent JSON parsing and FastAPI REST endpoint
requests and responses. Note: MedicalState TypedDict is defined in backend/graph/state.py.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict, model_validator


# =====================================================================
# CANONICAL STATUS ENUM
# =====================================================================

class ConsultationStatus(str, Enum):
    """Canonical consultation status enum used across DB, State, and API."""
    DRAFT = "DRAFT"                 # Consultation created / raw transcript uploaded
    PROCESSING = "PROCESSING"       # Multi-agent LangGraph pipeline executing
    AWAITING_APPROVAL = "AWAITING_APPROVAL" # Agent execution complete; awaiting doctor action
    APPROVED = "APPROVED"           # Doctor clicked "Approve & Save" (persisted to clinical_documents)
    REJECTED = "REJECTED"           # Doctor clicked "Reject & Discard"
    FAILED = "FAILED"               # Unrecoverable error in agent pipeline or transcription


# =====================================================================
# AGENT STRUCTURED OUTPUT SCHEMAS (Pydantic Models)
# =====================================================================

class SOAPNote(BaseModel):
    """Structured SOAP note model generated by Clinical Note Writer."""
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    subjective: str = Field(default="", description="Patient-reported history, symptoms, and chief complaint.")
    objective: str = Field(default="", description="Physical exam findings, vital signs, and lab results mentioned in text.")
    assessment: str = Field(default="", description="Primary clinical diagnosis, differential, or impression.")
    plan: str = Field(default="", description="Physician-stated treatment instructions, prescriptions, and next steps.")

    @model_validator(mode="before")
    @classmethod
    def unwrap_nested_or_capitalized(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "SOAPNote" in data and isinstance(data["SOAPNote"], dict):
                data = data["SOAPNote"]
            elif "soapnote" in data and isinstance(data["soapnote"], dict):
                data = data["soapnote"]
            
            normalized = {}
            for k, v in data.items():
                k_lower = k.lower()
                if k_lower in ["subjective", "objective", "assessment", "plan"]:
                    if isinstance(v, dict):
                        lines = []
                        for sub_k, sub_v in v.items():
                            if sub_v is not None:
                                if isinstance(sub_v, (dict, list)):
                                    lines.append(f"{sub_k}: {sub_v}")
                                else:
                                    lines.append(f"{sub_k}: {sub_v}")
                        normalized[k_lower] = "\n".join(lines)
                    elif isinstance(v, list):
                        normalized[k_lower] = "\n".join(str(item) for item in v if item is not None)
                    else:
                        normalized[k_lower] = str(v) if v is not None else ""
                else:
                    normalized[k] = v
            return normalized
        return data


class MedicalSummary(BaseModel):
    """Consultation and discharge summary model generated by Medical Summary Agent."""
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    chief_complaint: str = Field(default="", description="Primary reason for patient visit.")
    diagnosis: str = Field(default="", description="Primary confirmed diagnosis.")
    key_findings: List[str] = Field(default_factory=list, description="Bullet points of key exam/lab findings.")
    discharge_summary: str = Field(default="", description="Executive discharge and clinical summary text.")

    @model_validator(mode="before")
    @classmethod
    def normalize_medical_summary(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "MedicalSummary" in data and isinstance(data["MedicalSummary"], dict):
                data = data["MedicalSummary"]
            
            normalized = {}
            for k, v in data.items():
                k_lower = k.lower()
                if k_lower in ["chief_complaint", "diagnosis", "discharge_summary"]:
                    if isinstance(v, dict):
                        lines = [f"{sub_k}: {sub_v}" for sub_k, sub_v in v.items() if sub_v is not None]
                        normalized[k_lower] = "\n".join(lines)
                    elif isinstance(v, list):
                        normalized[k_lower] = "\n".join(str(item) for item in v if item is not None)
                    else:
                        normalized[k_lower] = str(v) if v is not None else ""
                elif k_lower in ["key_findings", "keyfindings"]:
                    if isinstance(v, dict):
                        findings = []
                        for sub_k, sub_v in v.items():
                            if isinstance(sub_v, list):
                                findings.extend(str(item) for item in sub_v if item is not None)
                            elif sub_v is not None:
                                findings.append(f"{sub_k}: {sub_v}")
                        normalized["key_findings"] = findings
                    elif isinstance(v, list):
                        normalized["key_findings"] = [str(item) for item in v if item is not None]
                    else:
                        normalized["key_findings"] = [str(v)] if v else []
                else:
                    normalized[k] = v
            return normalized
        return data


class MedicationOrder(BaseModel):
    """Individual medication order model formatted by Treatment Planner."""
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    name: str = Field(default="", description="Medication name explicitly mentioned by doctor.")
    dosage: str = Field(default="", description="Dosage (e.g. 500mg, 10mg).")
    frequency: str = Field(default="", description="Frequency (e.g. Every 6 hours PRN, QD, BID).")
    duration: str = Field(default="", description="Duration (e.g. 5 days, 14 days, Chronic).")


class TreatmentPlan(BaseModel):
    """Formatted treatment plan model generated by Treatment Planner."""
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    treatment_summary: str = Field(default="", description="High-level overview of physician-prescribed treatment.")
    medications: List[MedicationOrder] = Field(default_factory=list, description="List of doctor-stated medication orders.")
    monitoring_requirements: List[str] = Field(default_factory=list, description="Patient monitoring rules or vital sign re-checks.")

    @model_validator(mode="before")
    @classmethod
    def normalize_treatment_plan(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "TreatmentPlan" in data and isinstance(data["TreatmentPlan"], dict):
                data = data["TreatmentPlan"]
            
            normalized = {}
            for k, v in data.items():
                k_lower = k.lower()
                if k_lower in ["treatment_summary", "treatmentsummary"]:
                    if isinstance(v, dict):
                        lines = [f"{sub_k}: {sub_v}" for sub_k, sub_v in v.items() if sub_v is not None]
                        normalized["treatment_summary"] = "\n".join(lines)
                    else:
                        normalized["treatment_summary"] = str(v) if v is not None else ""
                elif k_lower in ["monitoring_requirements", "monitoringrequirements"]:
                    if isinstance(v, list):
                        normalized["monitoring_requirements"] = [str(item) for item in v if item is not None]
                    elif isinstance(v, dict):
                        normalized["monitoring_requirements"] = [f"{sub_k}: {sub_v}" for sub_k, sub_v in v.items() if sub_v is not None]
                    else:
                        normalized["monitoring_requirements"] = [str(v)] if v else []
                else:
                    normalized[k] = v
            return normalized
        return data


class FollowupPlan(BaseModel):
    """Follow-up plan and patient instructions model generated by Follow-up Coordinator."""
    followup_date: str = Field(description="Recommended follow-up date (YYYY-MM-DD) or timeframe.")
    tests_ordered: List[str] = Field(default_factory=list, description="Diagnostic tests, imaging, or lab orders.")
    patient_instructions: str = Field(description="Clear, patient-friendly home care and emergency warning instructions.")


class ReviewResult(BaseModel):
    """Documentation quality & safety audit result generated by Documentation Reviewer."""
    passed_qc: bool = Field(description="True if quality and completeness checks pass.")
    completeness_score: float = Field(description="Completeness ratio between 0.0 and 1.0.")
    issues: List[str] = Field(default_factory=list, description="Critical compliance or schema issues.")
    warnings: List[str] = Field(default_factory=list, description="Clinical warnings, allergy alerts, and ICD-10 suggestions.")


# =====================================================================
# REST API ENDPOINT REQUEST / RESPONSE MODELS
# =====================================================================

class TranscribeAudioResponse(BaseModel):
    """Response model for POST /api/v1/transcribe."""
    transcript: str
    duration_seconds: float


class ProcessConsultationRequest(BaseModel):
    """Request model for POST /api/v1/consultation/process."""
    patient_id: str = Field(description="Patient code (e.g. P-98214) or raw UUID.")
    doctor_id: str = Field(description="Attending physician UUID.")
    consultation_text: str = Field(description="Raw consultation transcript text.")
    audio_url: Optional[str] = Field(default=None, description="Optional audio file URL or path.")


class ProcessConsultationResponse(BaseModel):
    """Response model for POST /api/v1/consultation/process."""
    consultation_id: str
    status: ConsultationStatus


class ApproveConsultationRequest(BaseModel):
    """Request model for POST /api/v1/consultation/{consultation_id}/approve."""
    doctor_id: str = Field(description="Attending physician UUID.")
    final_soap_note: Dict[str, Any]
    final_summary: Dict[str, Any]
    final_treatment_plan: Dict[str, Any]
    final_followup_plan: Dict[str, Any]
    doctor_notes: Optional[str] = Field(default=None, description="Optional physician approval notes.")


class ApproveConsultationResponse(BaseModel):
    """Response model for POST /api/v1/consultation/{consultation_id}/approve."""
    success: bool
    document_id: str
    status: ConsultationStatus
    timestamp: str


class RejectConsultationRequest(BaseModel):
    """Request model for POST /api/v1/consultation/{consultation_id}/reject."""
    doctor_id: str = Field(description="Attending physician UUID.")
    rejection_reason: str = Field(description="Reason for rejecting consultation draft.")


class RejectConsultationResponse(BaseModel):
    """Response model for POST /api/v1/consultation/{consultation_id}/reject."""
    success: bool
    status: ConsultationStatus
    timestamp: str
