"""API Data Transfer Models & Enums Package.

Contains Pydantic models for structured agent JSON parsing and FastAPI REST endpoint
requests and responses. Note: MedicalState TypedDict is defined in backend/graph/state.py.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


# =====================================================================
# CANONICAL STATUS ENUM
# =====================================================================

class ConsultationStatus(str, Enum):
    """Canonical consultation status enum used across DB, State, and API."""
    DRAFT = "DRAFT"                 # Consultation created / raw transcript uploaded
    PROCESSING = "PROCESSING"       # Multi-agent LangGraph pipeline executing
    AWAITING_APPROVAL = "AWAITING_APPROVAL" # Agent execution complete; awaiting doctor action
    APPROVED = "APPROVED"           # Doctor clicked "Approve & Save" (persisted to clinical_documents)
    REJECTED = "REJECTED"           # Doctor clicked "Reject & Discard"
    FAILED = "FAILED"               # Unrecoverable error in agent pipeline or transcription


# =====================================================================
# AGENT STRUCTURED OUTPUT SCHEMAS (Pydantic Models)
# =====================================================================

class SOAPNote(BaseModel):
    """Structured SOAP note model generated by Clinical Note Writer."""
    subjective: str = Field(description="Patient-reported history, symptoms, and chief complaint.")
    objective: str = Field(description="Physical exam findings, vital signs, and lab results mentioned in text.")
    assessment: str = Field(description="Primary clinical diagnosis, differential, or impression.")
    plan: str = Field(description="Physician-stated treatment instructions, prescriptions, and next steps.")


class MedicalSummary(BaseModel):
    """Consultation and discharge summary model generated by Medical Summary Agent."""
    chief_complaint: str = Field(description="Primary reason for patient visit.")
    diagnosis: str = Field(description="Primary confirmed diagnosis.")
    key_findings: List[str] = Field(default_factory=list, description="Bullet points of key exam/lab findings.")
    discharge_summary: str = Field(description="Executive discharge and clinical summary text.")


class MedicationOrder(BaseModel):
    """Individual medication order model formatted by Treatment Planner."""
    name: str = Field(description="Medication name explicitly mentioned by doctor.")
    dosage: str = Field(description="Dosage (e.g. 500mg, 10mg).")
    frequency: str = Field(description="Frequency (e.g. Every 6 hours PRN, QD, BID).")
    duration: str = Field(description="Duration (e.g. 5 days, 14 days, Chronic).")


class TreatmentPlan(BaseModel):
    """Formatted treatment plan model generated by Treatment Planner."""
    treatment_summary: str = Field(description="High-level overview of physician-prescribed treatment.")
    medications: List[MedicationOrder] = Field(default_factory=list, description="List of doctor-stated medication orders.")
    monitoring_requirements: List[str] = Field(default_factory=list, description="Patient monitoring rules or vital sign re-checks.")


class FollowupPlan(BaseModel):
    """Follow-up plan and patient instructions model generated by Follow-up Coordinator."""
    followup_date: str = Field(description="Recommended follow-up date (YYYY-MM-DD) or timeframe.")
    tests_ordered: List[str] = Field(default_factory=list, description="Diagnostic tests, imaging, or lab orders.")
    patient_instructions: str = Field(description="Clear, patient-friendly home care and emergency warning instructions.")


class ReviewResult(BaseModel):
    """Documentation quality & safety audit result generated by Documentation Reviewer."""
    passed_qc: bool = Field(description="True if quality and completeness checks pass.")
    completeness_score: float = Field(description="Completeness ratio between 0.0 and 1.0.")
    issues: List[str] = Field(default_factory=list, description="Critical compliance or schema issues.")
    warnings: List[str] = Field(default_factory=list, description="Clinical warnings, allergy alerts, and ICD-10 suggestions.")


# =====================================================================
# REST API ENDPOINT REQUEST / RESPONSE MODELS
# =====================================================================

class TranscribeAudioResponse(BaseModel):
    """Response model for POST /api/v1/transcribe."""
    transcript: str
    duration_seconds: float


class ProcessConsultationRequest(BaseModel):
    """Request model for POST /api/v1/consultation/process."""
    patient_id: str = Field(description="Patient code (e.g. P-98214) or raw UUID.")
    doctor_id: str = Field(description="Attending physician UUID.")
    consultation_text: str = Field(description="Raw consultation transcript text.")
    audio_url: Optional[str] = Field(default=None, description="Optional audio file URL or path.")


class ProcessConsultationResponse(BaseModel):
    """Response model for POST /api/v1/consultation/process."""
    consultation_id: str
    status: ConsultationStatus


class ApproveConsultationRequest(BaseModel):
    """Request model for POST /api/v1/consultation/{consultation_id}/approve."""
    doctor_id: str = Field(description="Attending physician UUID.")
    final_soap_note: Dict[str, Any]
    final_summary: Dict[str, Any]
    final_treatment_plan: Dict[str, Any]
    final_followup_plan: Dict[str, Any]
    doctor_notes: Optional[str] = Field(default=None, description="Optional physician approval notes.")


class ApproveConsultationResponse(BaseModel):
    """Response model for POST /api/v1/consultation/{consultation_id}/approve."""
    success: bool
    document_id: str
    status: ConsultationStatus
    timestamp: str


class RejectConsultationRequest(BaseModel):
    """Request model for POST /api/v1/consultation/{consultation_id}/reject."""
    doctor_id: str = Field(description="Attending physician UUID.")
    rejection_reason: str = Field(description="Reason for rejecting consultation draft.")


class RejectConsultationResponse(BaseModel):
    """Response model for POST /api/v1/consultation/{consultation_id}/reject."""
    success: bool
    status: ConsultationStatus
    timestamp: str
